experiment_project: 'Mitty'
experiment_name: 'train'
model_id:    "/Path/to/Wan2.2-TI2V-5B-Diffusers"
output_root: '/Path/to/Output_Path'
use_DiffSynth: True
use_drop_text: True
use_lora: True

training:
  resume_path: ~
  batch_size: 2
  max_steps: 5000
  warmup_steps: 10
  learning_rate: 1e-4
  weight_decay: 1e-2
  save_val_interval_steps: 1000
  accumulate_grad_batches: 2
  gradient_clip_val: ~
  precision: "bf16-mixed"
  accelerator: "auto"
  strategy: 'auto'
  gradient_checkpointing: True
  benchmark: False

dataset:
  video_root:  '/Path/to/Human_Videos/' # human video path
  video_root2: '/Path/to/Robot_Videos/' # robot video path
  first_root:  '/Path/to/First_Frame/'  # first frame path, leave an empty directory (/Path/to/Empty/) if not used
  is_one2three: True
  height: 224
  width: 416
  sample_n_frames: 81
  fps: 24
  num_workers: 8
  shuffle: True
  drop_last: True 
  pin_memory: True
